# Generated by Django 4.1.4 on 2023-01-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_listing_category_alter_listing_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='initialPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
