# Generated by Django 4.1.4 on 2023-01-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_initialprice_alter_bid_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bidCount',
            field=models.IntegerField(default=0),
        ),
    ]
